# Enable C++ support
language: cpp

os: linux

# Compiler selection
compiler:
  - g++

# Build steps
script:
  - make
  - make reset
  - make biorobots-sample:
  - make cancer-biorobots-sample:
  - make cancer-immune-sample:
  - make virus-macrophage-sample:

notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
