# Enable C++ support
language: cpp

os: linux

# Compiler selection
compiler:
  - g++

# Build steps
script:
  - make

notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
