
# Enable C++ support
language: cpp

os: windows

# rf. https://github.com/tanzislam/cryptopals/blob/master/.travis.yml#L134-L146
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        ## $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        $msys2 pacman --sync --noconfirm --needed \
                make \
                mingw-w64-x86_64-libtool \
                mingw-w64-x86_64-toolchain
        # export MAKE=mingw32-make  # so that Autotools can find it
        taskkill //IM gpg-agent.exe //F
        export CPPFLAGS=-D__USE_MINGW_ANSI_STDIO=1
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export GNU_MAKE=/C/tools/msys64/usr/bin/make
        export MAKE=$GNU_MAKE
        export AR=gcc-ar
        export RANLIB=gcc-ranlib
        ;;
    esac

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

- g++ --version
- $shell $GNU_MAKE --version

install:
# - export BOOST_DIR=$PWD/boost
# - export GTEST_DIR=$PWD/googletest
# - export HUNSPELL_DIR=$PWD/hunspell
# - export CRYPTOPP_DIR=$PWD/cryptopp
# - export OPENSSL_DIR=$PWD/openssl
# - $GIT config --global --add submodule.fetchJobs `nproc`
# - export MAKEFLAGS="-s -j `nproc`"
- $shell ./prepare_deps

# Build steps
script:
  - $GNU_MAKE
#  - make biorobots-sample

notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
